project:
  type: website

website:
  title: "dass2024"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: "ホーム"
      - basics.qmd
      - model.qmd
      - var.qmd
      - enkf.qmd

appendix-style: plain

bibliography: refs.bib
csl: american-meteorological-society.csl

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

crossref:
  eq-prefix: ""