---
title: 演習課題
---

## 初級

平均、分散・共分散、線型回帰など基本的な統計の知識があることを前提とする。以下を参考に各自の興味でいろいろとアンサンブルカルマンフィルタや変分法について調べてみよう。

1. 風の単一観測の同化

 - 逐次EnKF/EAKFを実装する。
 - 観測を東西風$u$または$v$とみなすと、線型観測になる。観測を東西風$u$または$v$とみなして同化する。
 - 東西風及び南北風と風速は非線型の関係にあるため、解析されたアンサンブル平均の東西風及び南北風は最適ではない（suboptimal）。
 - 第一推定値の風速は観測される風速とは線型で、結合状態・観測ベクトルの最後に解析されているので、スクリプトを改変してプロットしてみよう。
 - アンサンブルメンバ数や第一推定値、予報及び観測誤差を変えてみる。
 - 観測演算子を$u$、$v$でそれぞれ微分し、線型化して$\mathbf{H}$を求める。実験のパラメタから予報誤差共分散行列$\mathbf{B}$及び観測誤差共分散行列$\mathbf{R}$を作成する。3DVarの解を求めて図に追加する[@Enomoto-Nakashita:2024]。
 - $|u|$のイノベーションと$u$または$v$のインクリメント散布図を作成し、風速EnKF/EAKFが線型回帰になっているか確認してみよう。
- さらに、風向とその誤差を決めて、風速と風向を順次同化するように改変してみよう。
  
2.（応用）Lorenz-63に4DVar及びEnKF/EAKFを適用し、両者を比較する。

- 変分法で最適化回数に対してコスト函数、勾配ノルム、解析誤差を描画する。
- 変分法の最適化回数やアンサンブルカルマンフィルタのメンバ数を変えてみる。
- モデルのパラメタを変えてみる。

## 中級

データ同化の基礎を理解していることを前提とする。

1. Lorenz-96の非線型モデル、接線型モデル、随伴モデルを実装する。
2. インフレーションと局所化をEAKFに導入する。
3. （応用）任意のモデルにEAKF、変分法を適用する。

## サンプルプログラム

GitHubの[tenomoto/dass2024](https://github.com/tenomoto/dass2024)から取得する。問題があれば、[issues](https://github.com/tenomoto/dass2024/issues)に報告してほしい。

- [Python](Python/index.html)
- [Fortran](Fortran/index.html)
- [R](R/index.html)