---
title: R
---
このディレクトリには、Rのスクリプトが格納されている。

## 共通モジュール

- `dist.R`: 距離計算
    * `lorenc`: 円周上の2点間の距離を計算。Lorenc私信[@Bowler-etal:2013]。局所化行列が半正定値になる。
    * `linear.periodic`: 円周上の格子点番号の差に基づく距離。二つの周り方のうち、近い方を返す。
    * `gc.5th`: @Gaspari-Cohn:1999 式(4.10)の5次の区分有理数函数。値が0になる距離の半分$c$はGaussianが$e^{-1/2}$倍となる距離のおよそ\sqrt{10/3}倍に相当する（中下私信）。
    * `ga`: Gaussian。値が$e^{-1/2}$倍となる距離をパラメタとして与える。
- `rk4.R`: 4次のRunge-Kutta法（RK4）
　　* `rk4`による時間積分。時間変化傾向を返す函数`f`、時刻`t`、1次元配列に格納した変数`y`、時間刻み幅`h`のほかに、`f`に渡すパラメタを1次元配列`opts`に格納して渡すことができる。
　　* `tl`: RK4の接線型。`f`の接線型`df`と接線型変数`dy`も渡す。
　　* `ad`: RK4の随伴。`f`の随伴`fa`と接線型変数`ya`も渡す。
- `step.R`: RK4による時間積分
    * `fom`: 前方モデル`f`で`nstep`積分する。
    * `tlm`: 前方モデル`f`と接線型モデル`df`で`nstep`積分する。
    * `adm`: 前方モデル`f`と随伴モデル`fa`で`nstep`から1まで逆向きに積分する。

## アンサンブルカルマンフィルタのモジュール

- `enkf.R`: `enkf_analysis`で一つの観測を同化して、インクリメントを返す。結合状態・観測空間の第一推定値`zf`、摂動を付与した観測`yo`をそれぞれ1次元配列で与える。観測誤差分散`r`はスカラ、予報共分散に対する局所化及びインフレーションを1次元配列で与える。
- `eakf.R`: `eakf.analysis`で一つの観測を同化して、インクリメントを返す。結合状態・観測空間の第一推定値`zf`1次元配列で与える。観測`yo`とその誤差分散`r`はスカラ、予報共分散に対する局所化及びインフレーションを1次元配列で与える。
- `eval.R`: `calc.error`にアンサンブルと真値を与えて、アンサンブル平均の誤差`e1`、アンサンブルメンバの誤差の平均`e2`、比`e1/e2`、比の期待値、期待値で規格化した比を計算する。[Anderson:2001,Whitaker-Hamill:2002]

## 風速観測

第一推定値の周り分布するアンサンブルから単一の観測を`run_wind_ens.R`で同化し描画できる。

- `run_wind_ens.R`: 単一の観測データをアンサンブルカルマンフィルタで同化する。ネームリスト`wind.nml`からパラメタを読み、第一推定値`zf`と解析値`za`を作成して描画する。
- `wind.nml`: 乱数の種`seed`、アンサンブル数`ne`、予報誤差標準偏差`zf`、東西及び南北風の第一推定値`uf, vf、`観測`yo`、観測誤差標準偏差`so`、同化アルゴリズム`eakf`または`enkf`を`fil`に設定する。

## Lorenz-63 モデル

初期の設定では @Huang-Yang:1996 に倣って、無次元時間$t=2$を時間刻み幅$\Delta t=0.01$で200ステップかけて積分する。観測間隔は60ステップに1回で、60、120、180ステップ目で行う。

- `l63.R`: @Lorenz:1963 モデル`l63`、接線型`tl`、接線型`ad`及びテストサブルーチン`test`が含まれる。RK4のインターフェースに合わせた時刻`t`は利用されない。予報3変数及び3つのパラメタは、それぞれ`w`と1次元配列`opts`に入れて渡す。
- `run_l63_ens.R`: `config_l63.R`のパラメタに基づき、アンサンブルカルマンフィルタで同化する。初期アンサンブル摂動と観測は正規乱数で生成する。真値`xt`、アンサンブル平均`xm`を曲線で、観測`yo`をマーカで描画する。
- `run_l63_var.R`: `config_l63.R`のパラメタに基づき、4次元変分法同化を行う。上述の時間を単一のウインドウとして初期値の推定を行う。背景誤差共分散は単位行列である。最急降下法で最適化する。真値`xt`最後の予報のアンサンブル平均`xb`を曲線で、、観測`yo`をマーカで描画
- `config_l63.R`: `p, r, b`はLorenz-63モデルのパラメタ、`dt`は時間刻み幅、`bgd.b`は背景誤差分散、`ni, a`はそれぞれ最適化の反復回数及びステップ幅、`model.q`は第一推定値の初期分散、`ne`はアンサンブル数、`fil`は同化アルゴリズム`eakf`または`enkf`。

## Lorenz-96モデル

アンサンブルカルマンフィルタと4次元変分法で共通して用いるテータを`prep_l96.R`で生成する。その後`run_l96_ens.R`または、`run_l96_var.R`を実行しデータ同化を行う。既定では、観測は40点全てに毎時刻ある。結果はRスクリプトで描画できる。

- `l96.R`: Lorenz-96モデル[@Lorenz-Emanuel:1998]`l96`及びその接線型`tl`、随伴`ad`並びにテストサブルーチン`test`が含まれる。
- `prep_l96.R`: `config_l96.R`からパラメタを取得し、真値、第一推定値のスピンアップを行うとともに、真値から観測を生成しファイルに保存する。
- `run_l96_ens.R`: `prep_l96.R`が生成したファイルからデータを読み、`config_l96.R`からパラメタを取得し、アンサンブルカルマンフィルタによりデータ同化を行う。`l96_`フィルタ名`.dat`に誤差と標準偏差を格納する。
- `run_l96_var.R`: `prep_l96.R`が生成したファイルからデータを読み、`config_l96.R`からパラメタを取得し、4次元変分法によりデータ同化を行い、`l96_var.dat`に誤差を格納する。
- `config_l96.R`: `ns`は状態の数、`dt`は時間刻み幅、`F`は強制　の大きさ、`nt.spinup`はスピンアップのステップ数、`nt`は同化のステップ数、`r`は観測誤差分散。`b`は背景誤差分散、`nw`はウインドウのステップ数、`ni`は最適化の最大反復回数、`a`はステップ幅、`gb`は勾配ノルムの閾値。`ne`はアンサンブル数、`fil`は`enkf`または`eakf`、`c.loc`は局所化係数が$e^{-1/2}$となる格子数。``xt.fname, yo.fname, xf.fname`は真値、観測、アンサンブルのファイル名。
- `plot_l96_ens.R`: `l96_`フィルタ名`.dat`からデータを、`config_l96.R`からパラメタを読み込み、アンサンブル平均の誤差及び標準偏差、アンサンブルの誤差の平均、観測誤差を描く。
- `plot_l96_var.R`: `l96_var.dat`からデータを、`config_l96.R`からパラメタを読み込み、解析誤差と観測誤差を描画く。